import SpottyDomain
import Foundation

/// Shared synthetic-data helpers for `OggVorbisDecoderChecks` and `VorbisDecodePipelineChecks`,
/// which both exercise the same kind of Ogg/Vorbis byte stream at different layers.

/// Loads the committed `tone-44100-stereo.ogg` resource. A missing file fails the suite, matching
/// the JSON fixtures in the same `Fixtures` copy — it does not skip-pass.
@MainActor
func bundledToneFixture(_ check: CheckRunner) -> Data? {
    var data: Data?
    check.noThrow("tone-44100-stereo.ogg is bundled") {
        data = try boundaryFixture(named: "tone-44100-stereo", extension: "ogg")
    }
    return data
}

/// LCG-generated bytes so a garbage-input check is deterministic across runs.
func lcgBytes(count: Int, seed: UInt64) -> [UInt8] {
    var state = seed
    var bytes = [UInt8]()
    bytes.reserveCapacity(count)
    for _ in 0..<count {
        state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
        bytes.append(UInt8(truncatingIfNeeded: state >> 56))
    }
    return bytes
}

/// Walks Ogg pages via `OggPageHeader.nextValidPage` to find the granule position of the last
/// page that finishes a packet (skipping the `-1` sentinel some pages carry, and any false-
/// positive `"OggS"` match inside packet payload bytes).
func lastGranulePosition(in data: Data) -> Int64? {
    var offset = 0
    var last: Int64?
    while let match = OggPageHeader.nextValidPage(in: data, from: offset), match.header.totalLength > 0 {
        if match.header.granulePosition != -1 {
            last = match.header.granulePosition
        }
        offset = match.offset + match.header.totalLength
    }
    return last
}
