#pragma once

/* This file is generated by cbindgen 0.29.4. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
/* Snapshot text fields may be NULL. */
typedef const char *_Nullable SpottyNullableCString;
#pragma clang assume_nonnull begin


// Connection observation delivered as a C struct. `device_id` and `last_error` are valid only
// for the callback; Swift must copy them before returning. Null means missing; outbound empty
// strings and strings containing an interior NUL are also delivered as null fields. Flags are
// 0 or 1.
//
// `credentials_rejected` is a typed, definitive streaming-credential rejection. It takes
// precedence over generic reconnect errors; it does not revoke the independent Keymaster
// grant.
//
// `resume_pending` is set only inside a reconnect's rehydration window: the session is
// connected and activated but `spirc_ready` is deliberately still 0, and Swift should issue
// its resume-load targets through `spotty_playback_load` now. Readiness is published once a
// Playing event lands, a load reports a dead Spirc, or the window times out.
typedef struct SpottyConnectionSnapshot {
  uint64_t revision;
  uint64_t session_generation;
  uint8_t session_connected;
  uint8_t spirc_ready;
  uint8_t is_active_device;
  uint8_t resume_pending;
  uint8_t credentials_rejected;
  SpottyNullableCString device_id;
  SpottyNullableCString last_error;
} SpottyConnectionSnapshot;

// Callback function type for connection state change notifications. Receives a typed snapshot;
// the snapshot pointer and its string pointers are valid only for the callback invocation.
typedef void (*ConnectionStateCallback)(const struct SpottyConnectionSnapshot*);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Registers a callback to receive connection state change notifications.
// Called whenever the connection state changes (connect, disconnect, error, etc.).
// The callback receives a C snapshot; string pointers are valid only for the call.
void spotty_playback_register_connection_state_callback(ConnectionStateCallback callback);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#pragma clang assume_nonnull end
